models/Quotations.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "quotations".
 *
 * @property integer $id
 * @property integer $job_id
 * @property string $filename
 * @property string $details
 * @property integer $status_id
 * @property string $drain_model
 * @property string $create_date
 * @property integer $created_by
 * @property string $update_date
 * @property integer $updated_by
 * @property string $status
 *
 * @property Statuses $status0
 * @property User $createdBy
 * @property User $updatedBy
 * @property Jobs $job
 */
class Quotations extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotations';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['job_id', 'label', 'details', 'status_id', 'drain_model', 'status'], 'required'],
            [['job_id', 'status_id', 'flow_rate', 'created_by', 'updated_by'], 'integer'],
            [['filename', 'details', 'drain_model','reasons', 'frame_guard'], 'string'],
            [['create_date', 'update_date'], 'safe'],
            [['status'], 'string', 'max' => 1],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => Statuses::className(), 'targetAttribute' => ['status_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['updated_by' => 'id']],
            [['job_id'], 'exist', 'skipOnError' => true, 'targetClass' => Jobs::className(), 'targetAttribute' => ['job_id' => 'id']],
        ];
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }
        
        if($this->isNewRecord){
            $this->created_by = Yii::$app->user->identity->id;
        }else{
            $this->created_by = $this->created_by;
            $this->updated_by = $this->updated_by;
        }
        return true;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'job_id' => 'Job ID',
            'filename' => 'Filename',
            'details' => 'Details',
            'status_id' => 'Status ID',
            'drain_model' => 'Drain Model',
            'frame_guard' => 'Frame Guard',
            'flow_rate' => 'Flow Rate',
            'label' => 'Label',
            'create_date' => 'Create Date',
            'created_by' => 'Created By',
            'update_date' => 'Update Date',
            'updated_by' => 'Updated By',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus0()
    {
        return $this->hasOne(Statuses::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJob()
    {
        return $this->hasOne(Jobs::className(), ['id' => 'job_id']);
    }
}

controllers/QuotationsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Quotations;
use app\models\QuotationsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use mPDF;
use app\models\Catchbasin;
use yii\helpers\ArrayHelper;						  

/**
 * QuotationsController implements the CRUD actions for Quotations model.
 */
class QuotationsController extends Controller
{
    public $existingDrains  = array();
    public $checkLength     = 0;
    public $allNodes        = array();
    public $preMaxLength    = 0;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Quotations models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new QuotationsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Quotations model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $userId = Yii::$app->user->getId();
        $query  = \app\models\Notifications::find()->where(['is_read' => '0', 'user_id' => $userId]);
        $query->andWhere("notificationtext like '%recordId=".$id."%'");
        $notificationData = $query->one();
        if($notificationData){
            $notificationData->is_read = 1;
            $notificationData->update_date = date('Y-m-d H:i:s');
            $notificationData->save();
        }
        

        $quoteRow = Quotations::find()->where(['id' => $id])->one();

        if(empty($quoteRow)){
            Yii::$app->getSession()->setFlash('error', 'Configuration has been removed !');
            return $this->redirect(['/jobs/list']);
        }
        return $this->render('view', [
             'quoteRow' => $quoteRow,
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Quotations model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {   

        $model = new Quotations();
        $modelFeature = new \app\models\FeaturesAll();
		 // Get Catch Basin Model by AM (Start)
        $modelCatchbasin = new \app\models\Catchbasin();
        // Get Catch Basin Model by AM (End)																																																																																					
        $modelFeatures = yii\helpers\ArrayHelper::map(\app\models\Featuretypes::find()->all(),'id','title');
        $modelGrateMaterial = yii\helpers\ArrayHelper::map(\app\models\FeaturesAll::find()->groupBy('grate_material')->all(),'suffix','grate_material');
        $modelGrateLoadRating = yii\helpers\ArrayHelper::map(\app\models\FeaturesAll::find()->groupBy('grate_load_rating')->all(),'id','grate_load_rating');
		
		// Get Catch Basin List of size by AM (Start)
        $lists = Catchbasin::find()->groupBy('catch_basin_size')->all();
        foreach($lists as $list){
        $a = $list->catch_basin_size = $list->catch_basin_size.'"'." Width";
        $b = $list->id = $list->catch_basin_size;
        }
        $modelCatchbasinsize = ArrayHelper::map($lists, 'catch_basin_size', 'catch_basin_size');
        // $modelCatchbasinsize = yii\helpers\ArrayHelper::map(\app\models\Catchbasin::find()->groupBy('catch_basin_size')->all(),'catch_basin_size', $list);
        // \app\components\Utility::debug($modelCatchbasinsize);exit;
        // Get Catch Basin List of size by AM (End)						 											   
        if (Yii::$app->request->post()) {
            $jobID = Yii::$app->request->get('jobid');
            $this::Calculation($jobID);
        } else {
            return $this->render('create', [
                'model' => $model,
                'modelFeatures'=>$modelFeatures,
                'modelFeature'=> $modelFeature,
                'modelGrateMaterial'=>$modelGrateMaterial,
                'modelGrateLoadRating'=>$modelGrateLoadRating,
				'modelCatchbasin'=>$modelCatchbasin,
                'modelCatchbasinsize'=>$modelCatchbasinsize,										  									
            ]);
        }
    }
		// Get Catch Basin Model by AM (Start)
	    public function actionGetCatchBasinSize() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) { 
                $trench_frame_id = $parents[0];
                $out = self::getCatchBasinSizeList($trench_frame_id); 
                echo Json::encode(['output'=>$out, 'selected'=>'']);
                return;
            }
        }
        echo Json::encode(['output'=>'', 'selected'=>'']);
    }
		// Get Catch Basin Model by AM (End)
		// Get Catch Basin Model List by AM (Start)
    public static function getCatchBasinSizeList($trench_frame_id){
        $data= \app\models\Catchbasin::find()->groupBy('catch_basin_size')
           ->where(['series_id'=>$trench_frame_id])
           ->select(['catch_basin_size as id',"(concat_ws('\" ',catch_basin_size,'Width')) AS name"])->asArray()->all();
        return $data;
    }										   					 
	// Get Catch Basin Model List by AM (End)
    //Simple Calculation 
    /*public function SimpleCalculation($jobID){

        $length = 53;
        $mod = $length%4;
        $divider = floor($length/4);
        if($mod == 0){

        }else{

            $innerDivider   = floor($divider/5); //full series
            $innderMod      =   $divider%5; //Remainig parts of series
            $remainingPart  = '';
            $drainsQuery    = \app\models\Drains::find()
            ->leftJoin('drainproducts as ds','drains.id=ds.drain_id')
            ->where(['drains.series_id' => 1])
            ->andWhere("ds.type='n' and drains.config = 'Sloped' and ds.product_code not like '%_N'")
            ->limit($divider)
            ->all();
            echo "<pre>";
            print_r($drainsQuery);
            exit;
            for ($seriesIndex=0;$seriesIndex<$innerDivider;$seriesIndex++) 
            {
                # code...

            }
        }
    }*/

    public function Calculation($jobID){
        if(Yii::$app->request->post()){
            $inputs = $nodes = $lines = array();
            foreach(Yii::$app->request->post() as $key => $val){
                if($val != ''){
                    if(strpos($key, 'nodes') > -1){
                        $key = str_replace('nodes_', '', $key);
                        preg_match('/images\/(.*).svg/', $val, $match);
                        $val = $match[1];
                        $nodes[$key] = $val;
                    }else if(strpos($key, 'lines') > -1){
                        $key = str_replace('lines_', '', $key);
                        $lines[$key] = $val;
                    }else if($key != '_csrf'){
                        $inputs[$key] = $val;
                    }
                    $inputs['nodes'] = $nodes;
                    $inputs['lines'] = $lines;
                    // echo $key.'---'.$val.'<br>';
                }
            }
            // exit;
        }

        if(count($inputs['lines']) == 0){
            Yii::$app->getSession()->setFlash('error', 'Please select Length from Grid!');
             return $this->redirect(['create','jobid'=>$jobID]);
        }
        $horPosition = $varPosition = '';
        $nodePosition = array_keys($inputs['nodes'])[0];
        foreach($lines as $key => $val){
            if(strpos($key, 'hor_') > -1){
                $horPosition = str_replace('hor_', '', $key);
            }
            if(strpos($key, 'var_') > -1){
                $varPosition = str_replace('var_', '', $key);
            }
        }
        
        if(!empty($horPosition)){
            list($xH, $yH) = explode('_', $horPosition);
        }
        if(!empty($varPosition)){
            list($xV, $yV) = explode('_', $varPosition);
        }
        if(!empty($nodePosition)){
            list($xO, $yO) = explode('_', $nodePosition);
        }

        $outletPosition = array();
        if($nodePosition == $horPosition && $nodePosition == $varPosition){
            $outletPosition = ['top', 'left'];
        }else if($horPosition == $nodePosition){
            $outletPosition = ['bottom', 'left'];
        }else if($varPosition == $nodePosition){
            $outletPosition = ['top', 'right'];
        }else if(@$xH == $xO && @$yH < $yO){
            $outletPosition = ['bottom', 'right'];
        }
        if(!isset($outletPosition[0])){
            // echo $xO.'...'.$xV;
            if ($xO < $xV){
                $outletPosition = ['top', 'right'];
            }else{
                $outletPosition = ['bottom', 'right'];
            }
        }
        $inputs['outletPosition'] = $outletPosition;
        // Get Catch Basin value by AM (Start)
        $outletType = '';
        
                if(!empty($inputs['Catchbasin']['catch_basin_size']))
                   {
                    $catch_basin_size = $inputs['Catchbasin']['catch_basin_size'];
                   }
                else
                   {
                    $catch_basin_size ='';
                   }
                if(!empty($inputs['Catchbasin']['trash_basket']))
                   {
                    $trash_basket = $inputs['Catchbasin']['trash_basket'];
                   }
                else
                   {
                    $trash_basket ='';
                   }
                // \app\components\Utility::debug($trash_basket);exit;
        // Get Catch Basin value by AM (End)										  

views/quotations/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\QuotationsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="quotations-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'job_id') ?>

    <?= $form->field($model, 'filename') ?>

    <?= $form->field($model, 'details') ?>

    <?= $form->field($model, 'status_id') ?>

    <?php // echo $form->field($model, 'drain_model') ?>

    <?php // echo $form->field($model, 'create_date') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'update_date') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/quotations/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Quotations */

$this->title = 'Create Quotations';
$this->params['breadcrumbs'][] = ['label' => 'Quotations', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="quotations-create">


    <?= $this->render('_form', [
        'model' => $model,
        'modelFeatures'=>$modelFeatures,
        'modelFeature'=> $modelFeature,
        'modelGrateMaterial'=>$modelGrateMaterial,
        'modelGrateLoadRating'=>$modelGrateLoadRating,
        'modelCatchbasin'=>$modelCatchbasin,
        'modelCatchbasinsize'=>$modelCatchbasinsize,
    ]) ?>

</div>

views/quotations/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\QuotationsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Configurations';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content-header">
  <div class="row">
    <h1 class="col-lg-4"><?= Html::encode("View Configurations") ?></h1>
    <div class="col-lg-8">
      <div class="pull-right">
        <?= Html::a('Add New', ['quotations/create','jobid'=>Yii::$app->request->get('id')], ['class' => 'btn btn-primary']) ?>
      </div>
    </div>
  </div>
</section>

<section class="content">
    <div class="quotations-index table-outer">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'label',
                [
                    'format' => 'raw',
                    'label' => 'Title',
                    'filter'=>'',
                    'value' =>function($data){
                        $title = json_decode($data->drain_model);
                        return $title[0];
                    }
                ],
                [
                    'format' => 'raw',
                    'label' => 'Status',
                    'filter'=>'',
                    'value' =>function($data){
                        if($data->status == '1'){
                            return $data->status0->title;
                        }else{ 
                            return "Not Requested";
                        } 
                    }
                ],
                'drain_model:ntext',
                'create_date',
    
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => "{view} {delete}",
                    'header'=> 'Action',
                    'buttons' => [
                        'view' => function ($url, $model, $key) {
                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['quotations/view','id'=>$model->id,'jobid'=>Yii::$app->request->get('id')]);
                        },
                        'delete' => function ($url, $model, $key) {
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['quotations/delete','id'=>$model->id],['data-confirm' => Yii::t('yii', 'Are you sure you want to delete this Member?'),'data-method'=>'post']);
                        }
                    ],
                ],
            ],'tableOptions' =>['class'=>'table table-striped table-paginate']
        ]); ?>
    </div>
</section>

views/quotations/pdf-view.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\components\Utility;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use kartik\mpdf\Pdf;

$this->title = 'View Configuration';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content-header">
    <div class="pull-right"><h4><b>Label</b><br/><?php echo $quoteData->label;?></h4></div>
    <div class=" col-sm-4">
        
        <div class="row">
            <div class="col-lg-9"><h3><?php echo @implode('<br>', json_decode($quoteData->drain_model));?></h3></div>
            
        </div>
        <table class="table table-striped">
            <?php   $components = array();
                    $x = 0;
                    // \app\components\Utility::debug(json_decode($quoteData->details));exit;
                    foreach(json_decode($quoteData->details) as $bs){ $bs = (array)$bs;
                        // \app\components\Utility::debug($bs[1]);exit;
                        if(isset($bs[0]) && $bs[0] == ''){
                            if(is_array($bs[2])){
                                $bs[2] = (array)$bs[2];
                            }
                            foreach($bs[2] as $row){
                                foreach($row as $drain => $qty){
                                    $length = 0;
                                    if(strpos($drain, '_N12') > -1){
                                        $length = 1;
                                    }else if(strpos($drain, '_N24') > -1){
                                        $length = 2;
                                    }else if(strpos($drain, '_N36') > -1){
                                        $length = 3;
                                    }else if(strpos($drain, '_N48') > -1){
                                        $length = 4;
                                    }else{
                                        $length = 4;
                                    }
                                    $components[$bs[1]][$x][$drain] = $length.'___'.$qty;
                                }
                                $x++;
                            }
                        }
                        if(isset($bs[1]) && $bs[1] == ''){
                        ?>
                        <tr>
                            <td style="font-size:11px;"><?php echo $bs[2];?></td>
                            <td style="font-size:11px;"><?php echo $bs[0];?></td>                        
                        </tr>
                <?php   } ?>
            <?php } ?>
        </table>
        
    </div>
    <div class="col-sm-8">
        <h3>Design Layout</h3>
        {{canvas_photo_here}}
    </div>
    <div class="clear"></div>
    
</section>

views/quotations/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Quotations */

$this->title = 'Update Quotations: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Quotations', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="quotations-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>